### ISSUE TITLE
Delta sourcing fails if GraphCMS webhook contains payload

### ISSUE THREAD

**Issue by ynnoj** [GraphCMS/gatsby-source-graphcms#100]

**Comment by notrab** [comment]
How does webhooks work currently? What is the required options in GraphCMS webhooks setup for preview/builds?

**Comment by ynnoj** [comment]
@notrab The toolkit exposes APIs to capture and action webhooks. If a re-build is triggered from a webhook, then the corresponding Gatsby node will be updated/created (via a GraphQL query) or deleted.

https://github.com/GraphCMS/gatsby-source-graphcms/blob/f3dba5560cb45e40c491e461db3d3a306fb8e6e6/gatsby-source-graphcms/gatsby-node.js#L88-L116

Right now you just need to setup your GraphCMS webhooks without payloads for builds and previews to be triggered. This issue is to address that.

Perhaps at some point we can use the payload from the webhook to update the Gatsby nodes, rather than firing a GraphQL query. However there's manual node work required for that so it's a bit more cumbersome.

**Comment by ynnoj** [comment]
Due to some [recent changes](https://www.notion.so/Webhook-Payload-Changes-63aa31f7027041f38fb35822b55bbfcb) to GraphCMS webhook payloads, this is no longer an issue.
