### ISSUE TITLE
Working with graphcms-fragments

### ISSUE THREAD

**Issue by notrab** [GraphCMS/gatsby-source-graphcms#115]
Currently if a few people are working on new branches, which includes work involving changes made to the GraphCMS schema, any new changes are brought in when you run the source plugin.

This can include models which perhaps aren't finished, and cause merge issues later down the line.

Could GraphCMS environments help here? We should document "working with graphcms-fragments" on the README for the best way to tackle this.

**Comment by ynnoj** [comment]
@notrab Great points! For sure need to document working with the query fragments (see #109).

GraphCMS Environments paired with a Git flow would be a nice combination, assuming the query fragments are checked into version control (as they should be).

Will close this, we can move discussion to #109.
