### ISSUE TITLE
Missing System Props (createdAt, ...)

### ISSUE THREAD

**Issue by phil-lgr** [GraphCMS/gatsby-source-graphcms#118]
As above, we are missing the system level timestamps

![image](https://user-images.githubusercontent.com/9644867/94223026-ece5a080-febc-11ea-8dcc-47766aaf1416.png)

**Comment by ynnoj** [comment]
@phil-lgr Thanks for reporting! I'll look at why these fields are missing from the schema. In the meantime you can add them to the generated `Asset` fragment manually: 

https://github.com/GraphCMS/gatsby-source-graphcms/blob/fe361131bac69a171f14226274b739b5bf62a9e0/demo/graphcms-fragments/Asset.graphql#L1-L18

**Comment by ynnoj** [comment]
Seems these fields (`createdAt`, `updatedAt`, `publishedAt`) are missing from fragments/types where localisation is present.

**Comment by phil-lgr** [comment]
Thank you!
