### ISSUE TITLE
Filter content stage accordingly to the API token settings

### ISSUE THREAD

**Issue by lanzoninicola** [GraphCMS/gatsby-source-graphcms#135]
Using the "gatsby-source-plugin" I can retrieve records only by the "default stage" configured in the API settings. I would ask to maintainers to let us to filter the content accordingly the "Content that can be queried" setting.  Reference: https://graphcms.slack.com/archives/C2VP3HAJH/p1603438442078400

**Comment by ynnoj** [comment]
@lanzoninicola Love for you to try this out!
