### ISSUE TITLE
Plugin not creating nodes for multi-line text field

### ISSUE THREAD

**Issue by moritzsalla** [GraphCMS/gatsby-source-graphcms#157]
I've created a multi-line text field with the name of "description" and filled it with dummy content. 

Even upon restarting the server and renaming the API ID, my query throws the following error:

```
Cannot query field "description" on type "GraphCMS_Project".
```

Gatsby: `2.22.10`
gatsby-source-graphcms: `2.1.1`

**Comment by ynnoj** [comment]
@moritzsalla Is the `description` field declared the generated query fragments? You can read more about them [here](https://github.com/GraphCMS/gatsby-source-graphcms#working-with-query-fragments).

**Comment by ynnoj** [comment]
Closing this, let me know if you're still encountering problems.
