### ISSUE TITLE
Slug field is unsupported

### ISSUE THREAD

**Issue by moritzsalla** [GraphCMS/gatsby-source-graphcms#158]
Gatsby cannot query slug field and throws an error.

**Comment by ynnoj** [comment]
@moritzsalla Can you provide more information here? What's the error? Is there a reproduction I can look at?

**Comment by moritzsalla** [comment]
Hi ynnoj, sorry for the lack of information. My post is more of a feature request than an error: I noticed that gatsby-source-graphcms appears to lack support for some newer graphCMS fields (e.x. slug). I've switched to using gatsby-source-graphql instead for now.

**Comment by ynnoj** [comment]
There's no reason why slug fields shouldn't be supported. They're just a string. 

Can you please check that the particular field you're having trouble querying is in the generated query fragment file? You can learn more [here](https://github.com/GraphCMS/gatsby-source-graphcms#working-with-query-fragments).

**Comment by ynnoj** [comment]
Closing this, let me know if you're still encountering problems.
