### ISSUE TITLE
Markdown Node is missing for RichText fields with multiple values

### ISSUE THREAD

**Issue by thomaseckhardt** [GraphCMS/gatsby-source-graphcms#159]
When using `gatsby-source-graphcms` with `buildMarkdownNodes` enabled, the markdown nodes for `RichText` fields are missing if "Allow multiple values" is checked in GraphCMS.

![image](https://user-images.githubusercontent.com/3824117/104943978-d2c55600-59b6-11eb-9619-4d510f8e9f05.png)

* gatsby v2.28.1
* gatsby-source-graphcms v2.1.1
* gatsby-plugin-mdx v1.6.0
* @mdx-js/mdx v1.6.22
* @mdx-js/react v1.6.22

**Comment by notrab** [comment]
This most likely can be resolved on this line https://github.com/GraphCMS/gatsby-source-graphcms/blob/e1b1627389903d25edafe1fa3c1e5b06dc5662cb/gatsby-source-graphcms/src/gatsby-node.js#L273 by checking the field type is an array.

I've added this to our todo list 🚀

**Comment by notrab** [comment]
I'm going to close this as with embedded types on Rich Text you can't have multiple values. So it's not something the plugin can support unfortunately.

We may reopen if we change the API behaviour.
