### ISSUE TITLE
Gatsby v3 & new Gatsby-Image support

### ISSUE THREAD

**Issue by ryanycoleman** [GraphCMS/gatsby-source-graphcms#169]
Do you plan to migrate this plugin to support [gatsby-plugin-image](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/) to build upon the other benefits [Gatsby v3](https://www.gatsbyjs.com/blog/gatsby-v3) provides? 

As a happy user of both Gatsby and GraphCMS, we're looking forward to finally taking advantage of image optimization for our GraphCMS Assets after having failed to take advantage of this source plugin and Gatsby-image.

**Comment by ynnoj** [comment]
Hey Ryan. This is on our radar, something we're hoping to implement in the next couple weeks.

**Comment by ryanycoleman** [comment]
🙌🏻 that's great! Feel free to ping us as early validators. We have a modest codebase and plan to upgrade into Gatsby v3 in mid/late March.

**Comment by ynnoj** [comment]
@ryanycoleman I just bumped the demo to use `gatsby@3.x.x` and `gatsby-plugin-image`. Works out of the box!

I'll add a `gatsbyImageData` resolver to all asset nodes in a separate PR. This will allow usage of `gatsby-plugin-image` without having to download local assets at build time.

**Comment by ynnoj** [comment]
@ryanycoleman See #171.

**Comment by ryanycoleman** [comment]
Woot! Thank you @ynnoj! We should be able to try this out as early as next week. Cheers.
