### ISSUE TITLE
Previous and next navigation for posts filtered by Category in Gatsby project not working

### ISSUE THREAD

**Issue by meesfrenkelfrank** [GraphCMS/gatsby-source-graphcms#196]
Somehow `previous` and `next` properties from context doesn't respect the filtered posts per Category?

I have a Category page template `src/templates/CategoryPage.tsx` where I have the following query to get the posts per category:

```
    type Props = {
      data: CategoryQueryQuery;
    };
    
    const CategoryPage = ({ data: { category } }: Props) => {
      const { categories } = useCategories();
      if (!category) return null;
      const categoryName = category?.name;
      const projects = category?.projects;
    
      return (
        <Layout>
          <h1>{categoryName}</h1>
          <CategoryList categories={categories} />
          <ProjectGrid projects={projects} />
        </Layout>
      );
    };
    
    export default CategoryPage;
    
    export const pageQuery = graphql`
      query CategoryQuery($slug: String!) {
        category: graphCmsCategory(slug: { eq: $slug }) {
          name
          slug
          projects {
            id: remoteId
            name
            slug
          }
        }
      }
    `;
```

From `gatsby-node.js` I pass `previous` and `next` thought the context:

```
    exports.createPages = async ({ graphql, actions: { createPage } }) => {
      const { data } = await graphql(`
        query Projects {
          projects: allGraphCmsProject(
            sort: { order: DESC, fields: createdAt }
            filter: { stage: { eq: PUBLISHED } }
          ) {
            edges {
              next {
                name
                slug
              }
              previous {
                name
                slug
              }
              node {
                slug
              }
            }
          }
          categories: allGraphCmsCategory {
            nodes {
              id: remoteId
              slug
            }
          }
        }
      `);
    
      const categories = data.categories.nodes;
    
      if (categories) {
        categories.forEach(({ id, slug }) =>
          createPage({
            path: `/projects/${slug}`,
            component: path.resolve('./src/templates/CategoryPage.tsx'),
            context: { id, slug },
          }),
        );
      }
    
      const projects = data.projects.edges;
    
      if (projects) {
        projects.forEach(({ node, previous, next }) => {
          createPage({
            path: `/projects/${node.slug}`,
            component: path.resolve('./src/templates/ProjectPage.tsx'),
            context: {
              slug: node.slug,
              previous,
              next,
            },
          });
        });
      }
    };
```

But now the `previous` and `next` properties doesn't respect the filtered posts array? So when there is only one post per category there should be no `previous` and `next` properties, but now they are..?

So the problem is that the `previous` and `next` properties from the `pageContext` counts all posts instead of the filtered posts array.

So what I want to achieve, is for example if you're in a category of the [E-commerce starter](https://www.gatsbyjs.com/starters/GraphCMS/gatsby-graphcms-ecommerce-starter) e.g. [Accessories](https://gatsby-graphcms-ecommerce-starter.netlify.app/en/categories/accessories), you have `previous` and `next` links to navigatie to `previous` and `next` products.

How do I solve this issue?

**Comment by spences10** [comment]
@meesfrenkelfrank so let me get this straight, there are `projects` from both the `PUBLISHED` and `DRAFT` stage being shown on the page?

And you only want to show `PUBLISHED` stage items? Correct?

I recall trying to do something similar in Gatsby a while back, but that was for local files, but the same sort of behaviour and I worked around it on the client. Maybe you could do something similar??

Could you add the `stage` in the Gatsby node query and check there? Maybe do a logic check there.

**Comment by meesfrenkelfrank** [comment]
@spences10 to get it clear. The problem is not the published or draft items. The problem is that when I am inside a category the `previous` and `next` links to navigate to `previous` and `next` items takes all the items instead of only the array of items inside that specific category. How do I solve that?

**Comment by notrab** [comment]
@meesfrenkelfrank is this still an issue?

Does the `next`/`previous` types have arguments to filter also?

I believe there was some Gatsby limitation with this a while back that I've no idea if the Gatsby team resolved.

I'll close this for now since it's been stale for a bit. Will reopen if we need to though.
