### ISSUE TITLE
sort out `npm publish` for 0.0.1

### ISSUE THREAD

**Issue by rdela** [GraphCMS/gatsby-source-graphcms#2]
@d-winter @flexzuu @redmega

**Comment by Redmega** [comment]
I can publish at some point in the next 3-4 hours. I can add you all as well so everyone has publish access. Or should we stick with one person as a gateway to release for now?

**Comment by rdela** [comment]
But they have an npm org, so I think what we need is to get you (and @hmeissner @rafacm and me if you want) with publish permissions for at least this package which @d-winter and @flexzuu can assist with I think. Do you have 2FA on @Redmega? Can we agree to make that and org requirement?

**Comment by rdela** [comment]
But if you want to publish under your personal before we get it all going go for it and we will just go around and update npm links later

**Comment by Redmega** [comment]
Sounds good. Wasn't sure how npm orgs worked, just thought someone had to publish it. I'll wait on input from them.

**Comment by rdela** [comment]
This is in the works 🎉
