### ISSUE TITLE
[gatsby-source-graphcms]: Problem building GraphCMS nodes // Error: Bad Request

### ISSUE THREAD

**Issue by orsi** [GraphCMS/gatsby-source-graphcms#205]
Public API, with default permissions (Read all models, Published stage)
https://api-ca-central-1.graphcms.com/v2/ckrikr0k50viq01xs8vhc5984/master

Commented out all queries to ensure that I didn't accidentally add non-existent properties. Still get this error with no idea what is happening -- the only thing I have setup is in the gatsby-config.js file:

![Screen Shot 2021-08-12 at 10 33 56 PM](https://user-images.githubusercontent.com/7156655/129296905-be5d9eaf-b68d-43b4-a6b8-9e8d911b17d1.png)

![Screen Shot 2021-08-12 at 10 31 39 PM](https://user-images.githubusercontent.com/7156655/129296732-c2e209ee-1fcf-4d43-8406-0c15c4bb551e.png)

![Screen Shot 2021-08-12 at 10 31 53 PM](https://user-images.githubusercontent.com/7156655/129296751-99c5cba5-0004-4c15-98c1-a9c1c46bae50.png)

**Comment by notrab** [comment]
This should be resolved in the latest `next` release. I believe it was to do with RichText fields having embeds enabled causing this, and swallowing the error.
