### ISSUE TITLE
Relation Field - When empty, throw an error on Gatsby

### ISSUE THREAD

**Issue by dotgreg** [GraphCMS/gatsby-source-graphcms#28]
Hello, thanks first for that plugin

I am running into an issue serving content from graphql using your plugin. When I empty a relation field, it is shown as non existent on gatsby graphql side, creating an error on graphql.

I see on the TODO that relationship are not supported, although, except from that problem, it is working really fine for me (relationship and localization included)
Screenshots below shows that problem is not reproduce on graphql graphcms side :

GRAPHCMS SIDE
![image](https://user-images.githubusercontent.com/2981891/35898900-554ccd96-0c04-11e8-8e56-7b5a92c7b654.png)
![image](https://user-images.githubusercontent.com/2981891/35898901-56970d24-0c04-11e8-9eab-c411ceb59adf.png)

GATSBY SIDE WHEN NO ITEM (type global and homepage
![image](https://user-images.githubusercontent.com/2981891/35898905-5bbdaff6-0c04-11e8-85cd-f5a4056af69a.png)
![image](https://user-images.githubusercontent.com/2981891/35898910-5e8d3a6c-0c04-11e8-9709-027fdab10fbe.png)

GATSBY SIDE WHEN AN ITEM HAS BEEN ADDED TO THE RELATION FIELD
![image](https://user-images.githubusercontent.com/2981891/35898919-64d13504-0c04-11e8-95a9-2c90f14466e5.png)

**Comment by Redmega** [comment]
cc: @rdela 

I believe this has to do with the fact that gatsby ignores empty nodes and doesn't create the type. I'll look into it later this week

**Comment by rdela** [comment]
Yes I think you can find people discussing this in Gatsby issues in relation to the WordPress and Contentful plugins if anyone is feeling intrepid.

**Comment by dotgreg** [comment]
saw those ones as well, they discuss directly on gatsby project issue tracking because the plugins themselves are maintained inside the core project codebase. But it looks being an issue with the plugins themselves, not from gatsby core.

**Comment by Redmega** [comment]
It's more related to the way gatsby internally creates types, I believe. If the field is empty the type will not be created.

@rdela Can you share links to those issues so I can read up? Can't seem to find them.

**Comment by rdela** [comment]
@redmega Here are a couple from a quick search
https://github.com/gatsbyjs/gatsby/issues/3495
https://github.com/gatsbyjs/gatsby/issues/2564

**Comment by danielmahon** [comment]
I was able to hack a workaround using `setFieldsOnGraphQLNodeType`. I added the following to `gatsby-node.js` to map a `coverImage: null` to `coverImage: { handle: '' }`. Then instead of checking for a null coverImage or handle in React, I check for an empty string.

```
exports.setFieldsOnGraphQLNodeType = (
  { type, store, pathPrefix, getNode, cache, reporter },
  pluginOptions
) => {
  if (type.name === 'Post') {
    // allow null coverImage fields
    type.nodes = type.nodes.map(node => {
      if (node.coverImage === null) {
        node.coverImage = {
          handle: '',
        };
      }
      return node;
    });
  }
};
```
Messy, but seems to work until they fix this. I'm honestly surprised Gatsby doesn't already support nullable fields...

**Comment by Kikobeats** [comment]
did you find how to handle this properly in the v2?
