### ISSUE TITLE
[beta] New GraphCMS API

### ISSUE THREAD

**Issue by dardub** [GraphCMS/gatsby-source-graphcms#32]
GraphCMS has announced a new Beta for a revised UI and API.  There will be breaking changes with this API so I'm assuming this plugin will need a migration and new version.

https://graphcms.com/blog/the-new-graphcms

**Comment by rdela** [comment]
Thanks for bringing this up, let us know as soon as you are on the beta in this issue and we can all start testing together on a new branch. We have a smaller update coming soon.

**Comment by dardub** [comment]
Just curious if anyone has been invited to the Beta yet?

**Comment by Redmega** [comment]
I have not been invited, yet. Will the invites be sent via email or within graphcms.com itself?

**Comment by belazer** [comment]
Hey guys! We are currently having a closed beta, that will open up at the end of next week! Send me your GraphCMS Account email and I will get you an invite today @Redmega @dardub!

**Comment by Redmega** [comment]
@rdela Have you had the chance to check out the beta yet? Unfortunately I've been swamped, things just _keep_ coming up for me.

**Comment by rdela** [comment]
Yes, hoping to resolve #16 as well check [Feature ideas > In progress](https://github.com/GraphCMS/gatsby-source-graphcms/projects/2) for updates on both.

**Comment by faia20** [comment]
The **New graphCMS version** is now official and stable, not beta anymore.
It would be nice to adapt this plugin to work with the new version or create a new one.
When I change the gatsby-config.js to take endpoint and token, I get:

error Plugin gatsby-source-graphcms returned an error
TypeError: Cannot read property '1' of null

**My gatsby-config.js:**

`module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: 'gatsby-source-graphcms',
      options: {
        endpoint: 'https://api-useast.graphcms.com/v1/........./master',
        token: '.....mytoken.....',
        query: `{
          artists {
            id
          }
        }`,
      },
    }
  ],
}
`

**Comment by jashmenn** [comment]
@faia20  - In the meantime, you can use: https://github.com/kbytin/gatsby-source-graphcms by @kbytin -- it's also published on npm here: https://www.npmjs.com/package/gatsby-source-graphcms-beta-patch

**Comment by belazer** [comment]
Gatsby also recently showcased this: https://github.com/gatsbyjs/rfcs/blob/native-graphql-support/text/0000-native-graphql-source.md

Should make the plugin obsolete when it releases 😊

**Comment by Redmega** [comment]
^ Generic graphql plugin looks like it would be great! Schema stitching is definitely the future.

Thanks for publishing a beta fix @jashmenn. If you create a PR with whatever changes were needed to fix it, we'd be happy to review and merge it!

I've been busy with work, sorry I've been less active with this repo!
