### ISSUE TITLE
[CircleCI](https://circleci.com)

### ISSUE THREAD

**Issue by rdela** [GraphCMS/gatsby-source-graphcms#4]
We have decided on CircleCI, using this issue to keep track of setup status

**Comment by Redmega** [comment]
Someone from @graphcms needs to authorize circleci for this project. I'm order to do that it needs org level access. Not sure if this is something they want. Does Travis have the same drawbacks?

**Comment by hmeissner** [comment]
I think org level access is what we have to deal with CI-wise. Will talk with GraphCMS folks about CircleCI in the morning.

**Comment by rdela** [comment]
I think we can send a Request that an org admin will have approve, or we can wait for them to add on their own

**Comment by rdela** [comment]
Access request pending and Daniel is on it 🚀

**Comment by rdela** [comment]
We are ready to set this up @Redmega want to do the honors or shall I give it a go?

**Comment by Redmega** [comment]
Thanks for taking the initiative @rdela I had some people over yesterday so I wasn't able to do much.

**Comment by rdela** [comment]
my fork now building on node 4,6,8, & 9, in parallel ⛓
4 https://circleci.com/gh/rdela/gatsby-source-graphcms/3
6 https://circleci.com/gh/rdela/gatsby-source-graphcms/5
8 https://circleci.com/gh/rdela/gatsby-source-graphcms/4
9 https://circleci.com/gh/rdela/gatsby-source-graphcms/6
all passed! so (assuming `faulty-keywords` tests are enough to judge) now we can modify babel config and know who we are breaking :boom:

config:
https://github.com/rdela/gatsby-source-graphcms/blob/master/.circleci/config.yml

@flexzuu @d-winter can we:
> owner of the team GitHub account (org) must go to the CircleCI [Add Project](https://circleci.com/add-projects), click the link to GitHub’s application permissions screen, and select Authorize CircleCI to enable members of the org to follow the project from their account.
https://circleci.com/docs/2.0/gh-bb-integration/#permissions-for-team-accounts

So we can add Circle to this repo? ⚫️

**Comment by rdela** [comment]
https://circleci.com/gh/GraphCMS/gatsby-source-graphcms
