### ISSUE TITLE
Unknown field `allCurrentEvents` on type `RootQueryType`

### ISSUE THREAD

**Issue by akalogiros** [GraphCMS/gatsby-source-graphcms#51]
Hello everyone,

i have created a graphcms endpoint and trying to fetch some data from there and show them in a demo website.

in my gatsby config i have the following setup:

```
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
  {
    resolve: `gatsby-source-graphcms`,
    options: {
      endpoint: `https://api.graphcms.com/simple/v1/MYENDPOINT`,
      token: `MYTOKEN`,
      query: `{
          allCurrentEvents {
          	tip
               awayteam
               hometeam
               date
          }
      }`,
    },
  }
],
}
```

from this setup i wanna fetch the tip,awayteam,hometeam & date and parse them to my site.

My problem is at index.js file where i have the below setup:

```
import React from 'react'
import PropTypes from 'prop-types'
import Helmet from 'react-helmet'

import Header from '../components/header'
import './index.css'

const Layout = ({ children, data }) => (
  <div>
    <Helmet
      title={data.site.siteMetadata.title}
      meta={[
        { name: 'description', content: 'Sample' },
        { name: 'keywords', content: 'sample, something' },
      ]}
    />
    <Header siteTitle={data.site.siteMetadata.title} />
    <Header siteTitle={data.site2.allCurrentEvents.tip} /> //trying to show my data here
    <div
      style={{
        margin: '0 auto',
        maxWidth: 960,
        padding: '0px 1.0875rem 1.45rem',
        paddingTop: 0,
      }}
    >
      {children()}
    </div>
  </div>
)

Layout.propTypes = {
  children: PropTypes.func,
}

export default Layout

export const query = graphql`
  query SiteTitleQuery {
    site {
      siteMetadata {
        title
      }
    }
  }
`
export const query2 = graphql`   //problematic query
  query SiteTitleQuery2 {
            allCurrentEvents{
              tip
            } 
        }
`
```
i am getting the following error

`GraphQL Error Unknown field `allCurrentEvents` on type `RootQueryType``

any ideas?

best,
a.

**Comment by hmeissner** [comment]
Hey @akalogiros, the problem you are running into is likely due to the fact that Gatsby takes the data it gets from your main config query and puts it in it's own data layer.

Because of this, the query you have to use in your app's code differs from what you would normally use when querying GraphCMS endpoint directly.

You can access `localhost:xxxx/___graphql` to see what gatsby did with the data from your endpoint and how to query for it.

**Comment by akalogiros** [comment]
Hello @hmeissner,

thanks a lot for your input.

I tried to do this over `localhost:xxxx/___graphql` but problem persist.

on the contrary when i am bulding my site with `gatsby develop` i can see in the command line that my data are correctly retrieved

![capture](https://user-images.githubusercontent.com/10164788/41251611-1bcfccf0-6dc3-11e8-98b7-d6d71f6d7ba4.PNG)

the error according `localhost:xxxx/___graphql` is at line `allCurrentEvents` & a`AllPastEvents` and its says `Cannot query field allCurrentEvents on type rootQueryType`

**Comment by hmeissner** [comment]
Yes this is all perfectly normal. You can see that Gatsby's graphiql is highlighting your queries as non-existent in the created API. You have to open up the docs on the right hand side in graphiql and look at how your data has been added to Gatsby. Then construct your queries according to that generated shape.

**Comment by hmeissner** [comment]
Closing this as that does not seem to be in issue with the plugin itself. Will reopen this if it turns out otherwise. If you have any more problems with this @akalogiros please PM me on our community Slack.
