### ISSUE TITLE
.babelrc, babel plugins, building and index.js noop

### ISSUE THREAD

**Issue by rdela** [GraphCMS/gatsby-source-graphcms#6]
@redmega [comment](https://github.com/GraphCMS/gatsby-source-graphcms/pull/1#issuecomment-344311426) on #1 review:
> Without the .babelrc we can't use stuff like spread operator or new feature imports or whatever... To the best of my knowledge, at least.
>Though I will say, I don't think we need babel-plugin-transform-runtime. Don't see it being used anywhere

@hmeissner in slack:
> do we need this noop with plugin decoupled? https://github.com/GraphCMS/gatsby-source-graphcms/blob/master/index.js

Let’s get CircleCI set up (#4) and testing oldest active node LTS, [6.12.0](https://nodejs.org/download/release/latest-v6.x/), and use it as baseline so we are not sayin “dunno builds for me”

[LTS schedule ](https://github.com/nodejs/LTS#release-schedule)

**Comment by Redmega** [comment]
> Let’s get CircleCI set up (#4) and testing oldest active node LTS, 6.12.0, and use it as baseline so we are not sayin “dunno builds for me”

 We can get concurrent builds up for 6 and 8. Open source projects get three parallel containers

As far as the noop, that's a @kyleamathews question.

**Comment by rdela** [comment]
Word we are go for Circle setup you want to handle @Redmega or want me to?

**Comment by rdela** [comment]
Circle success on node 4 for [`experimentally remove babel-plugin-transform-runtime`](https://github.com/rdela/gatsby-source-graphcms/commit/b29da171c867668e06df795770a3f52e92df593e)

builds
4 https://circleci.com/gh/rdela/gatsby-source-graphcms/8
6 https://circleci.com/gh/rdela/gatsby-source-graphcms/9
8 https://circleci.com/gh/rdela/gatsby-source-graphcms/10
9 https://circleci.com/gh/rdela/gatsby-source-graphcms/7

see also #4 🎉

**Comment by rdela** [comment]
Woohoo node 4 on Windows even! https://ci.appveyor.com/project/rdela/gatsby-source-graphcms/build/job/wlwvhf5g4sp3uw8j
