### ISSUE TITLE
Support for environment variables?

### ISSUE THREAD

**Issue by marcaaron** [GraphCMS/gatsby-source-graphcms#60]
Is there a current workaround for the need for an absolute url endpoint? 
Attempts to pass process.env.* fail with error.

**Comment by Redmega** [comment]
You should be able to use env. vars. For example that's how I'm using:

`process.env.GRAPHCMS_TOKEN`.

What is the error you're getting? How are you declaring the env var?

**Comment by marcaaron** [comment]
Ok! I think it must have been a silly typo. Seems to be working now.
