### ISSUE TITLE
Is this plugin outdated?

### ISSUE THREAD

**Issue by sundaycrafts** [GraphCMS/gatsby-source-graphcms#65]
I found the [official document](https://docs.graphcms.com/tutorials/developers/gatsby_and_graphcms) for GraphCMS 2.0. According to that, it seems only need the official plugin named `gatsby-source-graphql`.

Is this plugin outdated? Or what difference between the official plugin and this?

**Comment by gregoryforel** [comment]
It looks like `gatsby-source-graphql` will be the way to go. As far as I understand, the intention is to make it compatible to any GraphQL API provider by stitching their schema to Gatsby's, as opposed to having each provider developing their own. But... I might be wrong

**Comment by sundaycrafts** [comment]
Thank you for the answer!
I replaced `gatsby-source-graphql` from this plugin. And I haven't any problem for now. 
Please tell me if you find any issues using `gatsby-source-graphql` .

**Comment by Redmega** [comment]
Yeah, that's about right!

I haven't had much time to respond to these, sorry! `gatsby-source-graphql` is the way to go. This was written in the time before, when gatsby source plugins were the wild west 😉

**Comment by sundaycrafts** [comment]
I got it! Thank you!
